### ISSUE TITLE
Changes to task will not be applied until next run

### ISSUE THREAD

**Issue by SaraAdineh** [zulily/omicron#24]
If you apply changes to a running job(tasks) e.g. changing sla.minutes.since.success param, The changes will not be affected until next run of that job. In order to force the job to pick up changes immediately, we need to kill the running task and restart it again! It would be nice to avoid.

**Comment by CBrophy** [comment]
Won't fix. There's nothing to do while a task is running. The existing task must be killed to effect changes.
